$defs:
  AttributeModel:
    description: 'Base class for the attributes


      Contains:

      - id: The id of the attribute

      - id_interface: The id of the attribute on the interface (if not set, the id
      is used)

      - type: The type of the attribute

      - value: The value of the attribute

      - unit: The unit of the attribute

      - datatype: The datatype of the attribute

      - timestamp: The timestamp of the attribute'
    properties:
      id:
        title: Id
        type: string
      id_interface:
        title: Id Interface
        type: string
      type:
        allOf:
        - $ref: '#/$defs/AttributeTypes'
        default: value
      value:
        anyOf:
        - type: string
        - type: number
        - type: integer
        - type: boolean
        - type: object
        - items: {}
          type: array
        - type: 'null'
        default: null
        title: Value
      unit:
        anyOf:
        - $ref: '#/$defs/DataUnits'
        - type: 'null'
        default: null
      datatype:
        allOf:
        - $ref: '#/$defs/DataType'
        default: Number
      timestamp:
        anyOf:
        - format: date-time
          type: string
        - type: 'null'
        default: null
        title: Timestamp
    required:
    - id
    title: AttributeModel
    type: object
  AttributeTypes:
    description: Enum class for the attribute types
    enum:
    - timeseries
    - value
    title: AttributeTypes
    type: string
  CommandModel:
    description: 'Base class for the commands


      Contains:

      - id: The id of the command

      - id_interface: The id of the command on the interface (if not set, the id is
      used)

      - value: The value of the command'
    properties:
      id:
        title: Id
        type: string
      id_interface:
        title: Id Interface
        type: string
      value:
        anyOf:
        - type: string
        - type: integer
        - type: number
        - items: {}
          type: array
        - type: object
        - type: 'null'
        default: null
        title: Value
    required:
    - id
    title: CommandModel
    type: object
  ControllerComponentModel:
    description: 'Model for the configuration of the controller components.

      TODO: - Improve the model'
    properties:
      active:
        default: true
        title: Active
        type: boolean
      id:
        title: Id
        type: string
      type:
        anyOf:
        - $ref: '#/$defs/ControllerComponents'
        - type: string
        title: Type
      inputs:
        title: Inputs
        type: object
      outputs:
        title: Outputs
        type: object
      config:
        title: Config
        type: object
    required:
    - id
    - type
    - inputs
    - outputs
    - config
    title: ControllerComponentModel
    type: object
  ControllerComponents:
    description: Enum class for the controller components, could be extended by the
      needed components
    enum:
    - storage_controller
    - energytrendband_controller
    - hygienic_controller
    title: ControllerComponents
    type: string
  ControllerSettingModel:
    description: 'Model for the configuration of the controller settings.


      Contains:

      - time_settings: The time settings for the controller

      - specific_settings: The specific settings for the controller - not defined
      as a model


      TODO: What is needed here?'
    properties:
      time_settings:
        $ref: '#/$defs/TimeSettingsModel'
      specific_settings:
        anyOf:
        - type: object
        - type: 'null'
        default: {}
        title: Specific Settings
    required:
    - time_settings
    title: ControllerSettingModel
    type: object
  DataType:
    description: 'When possible reuse schema.org data types

      (Text, Number, DateTime, StructuredValue, etc.).

      Remember that null is not allowed in NGSI-LD and

      therefore should be avoided as a value.


      https://schema.org/DataType'
    enum:
    - Boolean
    - Date
    - DateTime
    - Number
    - Integer
    - Float
    - Text
    - Time
    - Relationship
    - StructuredValue
    - Array
    - Object
    - command
    - commandResult
    - commandStatus
    - geo:json
    title: DataType
    type: string
  DataUnits:
    description: "Possible units for the data\nUnits which are defined by Unit Code\
      \ (https://unece.org/trade/cefact/UNLOCODE-Download \nor https://github.com/RWTH-EBC/FiLiP/blob/master/filip/data/unece-units/units_of_measure.csv)\n\
      or here: https://unece.org/fileadmin/DAM/cefact/recommendations/rec20/rec20_rev3_Annex3e.pdf\n\
      TODO:\n    - Is there a better way to handle the units?\n    - Add more units?"
    enum:
    - SEC
    - HUR
    - CEL
    - LIT
    - MTW
    - MQH
    - WTT
    - WHR
    - KWH
    - CMT
    - MTR
    - MTK
    - MTS
    - P1
    - OHM
    - VLT
    title: DataUnits
    type: string
  InputModel:
    description: 'Model for the configuration of inputs.


      Contains:

      - id: The id of the input

      - interface: The interface of the input

      - id_interface: The id of the input on the interface

      - attributes: The attributes of the'
    properties:
      id:
        title: Id
        type: string
      interface:
        $ref: '#/$defs/Interfaces'
      id_interface:
        title: Id Interface
        type: string
      attributes:
        items:
          $ref: '#/$defs/AttributeModel'
        title: Attributes
        type: array
    required:
    - id
    - interface
    - id_interface
    - attributes
    title: InputModel
    type: object
  InterfaceModel:
    description: 'Base class for the interfaces

      TODO: - How to use this model?'
    properties:
      mqtt:
        default: false
        title: Mqtt
        type: boolean
      fiware:
        default: false
        title: Fiware
        type: boolean
      file:
        default: false
        title: File
        type: boolean
    title: InterfaceModel
    type: object
  Interfaces:
    description: Enum class for the interfaces
    enum:
    - mqtt
    - fiware
    - file
    title: Interfaces
    type: string
  OutputModel:
    description: 'Model for the configuration of outputs.


      Contains:

      - id: The id of the output

      - interface: The interface of the output

      - id_interface: The id of the output on the interface

      - attributes: The attributes of the output'
    properties:
      id:
        title: Id
        type: string
      interface:
        $ref: '#/$defs/Interfaces'
      id_interface:
        title: Id Interface
        type: string
      attributes:
        items:
          $ref: '#/$defs/AttributeModel'
        title: Attributes
        type: array
      commands:
        items:
          $ref: '#/$defs/CommandModel'
        title: Commands
        type: array
    required:
    - id
    - interface
    - id_interface
    - attributes
    - commands
    title: OutputModel
    type: object
  StaticDataModel:
    description: 'Model for the configuration of inputs.


      Contains:

      - id: The id of the input

      - interface: The interface of the input

      - id_interface: The id of the input on the interface

      - attributes: The attributes of the'
    properties:
      id:
        title: Id
        type: string
      interface:
        $ref: '#/$defs/Interfaces'
      id_interface:
        title: Id Interface
        type: string
      attributes:
        items:
          $ref: '#/$defs/AttributeModel'
        title: Attributes
        type: array
    required:
    - id
    - interface
    - id_interface
    - attributes
    title: StaticDataModel
    type: object
  TimeSettingsCalculationModel:
    description: 'Base class for the calculation time settings of the controller /
      system.


      Contains:

      - timerange: The timerange for the calculation (if only one value is needed
      and primary value,

      otherwise use timerange_min and timerange_max)

      - timerange_min: The minimum timerange for the calculation (only used if timerange
      is not set

      and timerange_max is set too)

      - timerange_max: The maximum timerange for the calculation (only used if timerange
      is not set

      and timerange_min is set too)

      - timerange_type: Type of time period, relative to the last result or absolute
      at the current

      time (if not set, the default type is absolute)

      - timerange_unit: The unit of the timerange (if not set, the default unit is
      minute)

      - timestep: The timestep for the calculation (if not set, the default value
      is 1), the

      related unit is defined in the timestep_unit attribute

      - timestep_unit: The unit of the timestep (if not set, the default unit is second)

      - sampling_time: The sampling time for the calculation (if not set, the default
      value is 1),

      the related unit is defined in the sampling_time_unit attribute

      - sampling_time_unit: The unit of the sampling time (if not set, the default
      unit is minute)'
    properties:
      timerange:
        anyOf:
        - type: number
        - type: 'null'
        default: null
        title: Timerange
      timerange_min:
        anyOf:
        - type: number
        - type: 'null'
        default: null
        title: Timerange Min
      timerange_max:
        anyOf:
        - type: number
        - type: 'null'
        default: null
        title: Timerange Max
      timerange_type:
        anyOf:
        - $ref: '#/$defs/TimerangeTypes'
        - type: 'null'
        default: absolute
      timerange_unit:
        anyOf:
        - $ref: '#/$defs/TimeUnits'
        - type: 'null'
        default: minute
      timestep:
        anyOf:
        - type: number
        - type: integer
        default: 1
        title: Timestep
      timestep_unit:
        allOf:
        - $ref: '#/$defs/TimeUnits'
        default: second
      sampling_time:
        anyOf:
        - type: number
        - type: integer
        default: 1
        title: Sampling Time
      sampling_time_unit:
        allOf:
        - $ref: '#/$defs/TimeUnits'
        default: minute
    title: TimeSettingsCalculationModel
    type: object
  TimeSettingsCalibrationModel:
    description: 'Base class for the calibration time settings of the controller /
      system.


      Contains:

      - timerange: The timerange for the calibration (if not set, the default value
      is 1),

      the related unit is defined in the timerange_unit attribute

      - timerange_unit: The unit of the timerange (if not set, the default unit is
      minute)

      - timestep: The timestep for the calibration (if not set, the default value
      is 1),

      the related unit is defined in the timestep_unit attribute

      - timestep_unit: The unit of the timestep (if not set, the default unit is second)

      - sampling_time: The sampling time for the calibration (if not set, the default
      value is 1),

      the related unit is defined in the sampling_time_unit attribute

      - sampling_time_unit: The unit of the sampling time (if not set, the default
      unit is day)'
    properties:
      timerange:
        anyOf:
        - type: number
        - type: 'null'
        default: null
        title: Timerange
      timerange_unit:
        anyOf:
        - $ref: '#/$defs/TimeUnits'
        - type: 'null'
        default: minute
      timestep:
        anyOf:
        - type: number
        - type: integer
        default: 1
        title: Timestep
      timestep_unit:
        allOf:
        - $ref: '#/$defs/TimeUnits'
        default: second
      sampling_time:
        anyOf:
        - type: number
        - type: integer
        default: 1
        title: Sampling Time
      sampling_time_unit:
        allOf:
        - $ref: '#/$defs/TimeUnits'
        default: day
    title: TimeSettingsCalibrationModel
    type: object
  TimeSettingsModel:
    description: 'Base class for the time settings of the controller / system.


      Contains:

      - calculation: The timeranges and settings für the calculation

      - calibration: The timeranges and settings for the calibration

      - results: The timesettings for the results


      TODO: Add the needed fields - calibration?'
    properties:
      calculation:
        $ref: '#/$defs/TimeSettingsCalculationModel'
      calibration:
        anyOf:
        - $ref: '#/$defs/TimeSettingsCalibrationModel'
        - type: 'null'
        default: null
      results:
        anyOf:
        - $ref: '#/$defs/TimeSettingsResultsModel'
        - type: 'null'
        default: null
    required:
    - calculation
    title: TimeSettingsModel
    type: object
  TimeSettingsResultsModel:
    description: Settings for the timesteps of the results.
    properties:
      timestep:
        anyOf:
        - type: number
        - type: integer
        default: 1
        title: Timestep
      timestep_unit:
        allOf:
        - $ref: '#/$defs/TimeUnits'
        default: second
    title: TimeSettingsResultsModel
    type: object
  TimeUnits:
    description: 'Possible time units for the time series data


      TODO: Is it better to use standard time units? Like in the unit code?'
    enum:
    - second
    - minute
    - hour
    - day
    - month
    title: TimeUnits
    type: string
  TimerangeTypes:
    description: 'Enum class for the timedelta types


      Contains:

      - ABSOLUTE: The timedelta is calculated from the actual time

      - RELATIVE: The timedelta is calculated from the last timestamp'
    enum:
    - absolute
    - relative
    title: TimerangeTypes
    type: string
description: 'Base Model for the configuration


  Contains:

  - interfaces: The interfaces of the system controller

  - inputs: The inputs of the system controller

  - outputs: The outputs of the system controller

  - staticdata: The static configuration data for devices the system controller

  - controller_components: The components of the controller

  - controller_settings: The settings for the controller'
properties:
  interfaces:
    $ref: '#/$defs/InterfaceModel'
  inputs:
    items:
      $ref: '#/$defs/InputModel'
    title: Inputs
    type: array
  outputs:
    items:
      $ref: '#/$defs/OutputModel'
    title: Outputs
    type: array
  staticdata:
    items:
      $ref: '#/$defs/StaticDataModel'
    title: Staticdata
    type: array
  controller_components:
    items:
      $ref: '#/$defs/ControllerComponentModel'
    title: Controller Components
    type: array
  controller_settings:
    $ref: '#/$defs/ControllerSettingModel'
required:
- interfaces
- inputs
- outputs
- staticdata
- controller_components
- controller_settings
title: ConfigModel
type: object
